#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${SCRIPT_DIR}/../.." && pwd)"

DEFAULT_RESUME="${REPO}/.local_runs/rm75_active6_v5_train_postcontactwrist_950k_20260625_211654/models/best.pt"
RESUME_MODEL="${RESUME_MODEL:-${DEFAULT_RESUME}}"

if [[ ! -f "${RESUME_MODEL}" ]]; then
  echo "Missing RESUME_MODEL: ${RESUME_MODEL}" >&2
  exit 1
fi

export VIVIDEX_HEADLESS_NO_RENDER="${VIVIDEX_HEADLESS_NO_RENDER:-1}"
export ACTIVE6_URDF="${ACTIVE6_URDF:-${REPO}/assets/robot/rm75_inspire_right/urdf/rm75_inspire_hand_right_active6_nocyl.urdf}"
export VIVIDEX_RM75_FINGER_FORCE_LIMIT="${VIVIDEX_RM75_FINGER_FORCE_LIMIT:-300}"
export VIVIDEX_RM75_FINGER_STIFFNESS="${VIVIDEX_RM75_FINGER_STIFFNESS:-600}"
export VIVIDEX_RM75_FINGER_DAMPING="${VIVIDEX_RM75_FINGER_DAMPING:-120}"
export VIVIDEX_RM75_STATIC_FRICTION="${VIVIDEX_RM75_STATIC_FRICTION:-6.0}"
export VIVIDEX_RM75_DYNAMIC_FRICTION="${VIVIDEX_RM75_DYNAMIC_FRICTION:-5.0}"
export VIVIDEX_RM75_RESTITUTION="${VIVIDEX_RM75_RESTITUTION:-0.0}"
export VIVIDEX_YCB_STATIC_FRICTION="${VIVIDEX_YCB_STATIC_FRICTION:-6.0}"
export VIVIDEX_YCB_DYNAMIC_FRICTION="${VIVIDEX_YCB_DYNAMIC_FRICTION:-5.0}"
export VIVIDEX_YCB_RESTITUTION="${VIVIDEX_YCB_RESTITUTION:-0.0}"

export RUN_NAME="${RUN_NAME:-rm75_active6_v9_lift_contact_$(date +%Y%m%d_%H%M%S)}"
export TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-1350000}"
export EVAL_FREQ="${EVAL_FREQ:-25000}"
export EVAL_N_EPISODES="${EVAL_N_EPISODES:-20}"
export SAVE_FREQ="${SAVE_FREQ:-50000}"
export RESTORE_FREQ="${RESTORE_FREQ:-50000}"
export N_ENVS="${N_ENVS:-8}"
export N_EVAL_ENVS="${N_EVAL_ENVS:-2}"

OVERRIDES=(
  "resume_model=${RESUME_MODEL}"
  "agent.params.resume_load_optimizer=False"
  "++env.task_kwargs.rm75_default_approach_delta=[0.02,-0.03,-0.01]"
  "++env.task_kwargs.rm75_arm_action_scale=0.26"
  "++env.task_kwargs.rm75_post_pregrasp_arm_ramp_steps=10"
  "++env.task_kwargs.rm75_post_pregrasp_arm_scale_start=0.035"
  "++env.task_kwargs.rm75_post_pregrasp_arm_scale_end=0.26"
  "++env.task_kwargs.rm75_post_pregrasp_hold_until_stable=True"
  "++env.task_kwargs.rm75_post_pregrasp_hold_arm_scale=0.025"
  "++env.task_kwargs.rm75_post_pregrasp_required_stable_hold_steps=2"
  "++env.task_kwargs.rm75_post_contact_lift_assist=True"
  "++env.task_kwargs.rm75_post_contact_lift_min_hold_steps=1"
  "++env.task_kwargs.rm75_post_contact_lift_min_non_thumb_contacts=1"
  "++env.task_kwargs.rm75_post_contact_lift_requires_thumb=False"
  "++env.task_kwargs.rm75_post_contact_max_xy_speed=0.008"
  "++env.task_kwargs.rm75_post_contact_max_down_speed=0.001"
  "++env.task_kwargs.rm75_post_contact_max_up_speed=0.060"
  "++env.task_kwargs.rm75_post_contact_lift_bias=0.014"
  "++env.task_kwargs.rm75_post_contact_max_angular_speed=0.16"
  "++env.task_kwargs.rm75_post_contact_wrist_bias=[-0.10,-0.35,0.0]"
  "++env.task_kwargs.rm75_post_contact_wrist_min_hold_steps=1"
  "++env.task_kwargs.rm75_post_contact_wrist_min_non_thumb_contacts=1"
  "++env.task_kwargs.rm75_post_contact_wrist_requires_thumb=False"
  "++env.task_kwargs.rm75_hand_close_bias=0.030"
  "++env.task_kwargs.rm75_hand_dynamic_close_bias=0.95"
  "++env.task_kwargs.rm75_hand_dynamic_close_start=0.300"
  "++env.task_kwargs.rm75_hand_dynamic_close_full=0.085"
  "++env.task_kwargs.rm75_hand_dynamic_close_gate_mode=blend"
  "++env.task_kwargs.rm75_hand_dynamic_close_requires_contact=False"
  "++env.task_kwargs.rm75_hand_dynamic_close_palm_weight=0.70"
  "++env.task_kwargs.rm75_hand_dynamic_close_finger_weight=0.30"
  "++env.task_kwargs.rm75_hand_dynamic_close_warmup_steps=0"
  "++env.task_kwargs.rm75_hand_dynamic_close_ramp_steps=10"
  "++env.task_kwargs.rm75_hand_dynamic_close_alpha_smooth=0.16"
  "++env.task_kwargs.rm75_hand_dynamic_close_contact_hold_steps=1"
  "++env.task_kwargs.rm75_hand_dynamic_close_contact_lock_alpha=1.0"
  "++env.task_kwargs.rm75_hand_dynamic_close_contact_boost=0.85"
  "++env.task_kwargs.rm75_hand_dynamic_close_phase_weight=0.65"
  "++env.task_kwargs.rm75_hand_dynamic_close_phase_start=0"
  "++env.task_kwargs.rm75_hand_dynamic_close_phase_ramp=10"
  "++env.task_kwargs.rm75_hand_dynamic_close_phase_near_gate=0.300"
  "++env.task_kwargs.rm75_hand_dynamic_close_group_mode=ratio"
  "++env.task_kwargs.rm75_hand_dynamic_close_thumb_ratio=0.95"
  "++env.task_kwargs.rm75_hand_dynamic_close_pinky_ratio=0.95"
  "++env.task_kwargs.rm75_hand_precontact_close_cap=0.72"
  "++env.task_kwargs.rm75_hand_precontact_thumb_cap=0.60"
  "++env.task_kwargs.rm75_hand_precontact_pinky_cap=0.62"
  "++env.task_kwargs.rm75_hand_close_bias_weights=[0.88,0.95,1.08,1.08,1.06,0.98]"
  "++env.task_kwargs.reward_kwargs.no_contact_grace_steps=28"
  "++env.task_kwargs.reward_kwargs.required_non_thumb_contacts=2"
  "++env.task_kwargs.reward_kwargs.contact_reward_scale=0.20"
  "++env.task_kwargs.reward_kwargs.thumb_contact_reward_scale=2.4"
  "++env.task_kwargs.reward_kwargs.non_thumb_contact_reward_scale=3.2"
  "++env.task_kwargs.reward_kwargs.palm_contact_reward_scale=8.0"
  "++env.task_kwargs.reward_kwargs.stable_contact_bonus=18.0"
  "++env.task_kwargs.reward_kwargs.contact_hold_bonus_scale=12.0"
  "++env.task_kwargs.reward_kwargs.contact_hold_bonus_steps=8"
  "++env.task_kwargs.reward_kwargs.object_reward_requires_contact=True"
  "++env.task_kwargs.reward_kwargs.object_reward_requires_stable_contact=False"
  "++env.task_kwargs.reward_kwargs.object_reward_contact_hold_steps=2"
  "++env.task_kwargs.reward_kwargs.object_reward_scale=7.0"
  "++env.task_kwargs.reward_kwargs.obj_err_scale=30.0"
  "++env.task_kwargs.reward_kwargs.hand_close_reward_scale=12.0"
  "++env.task_kwargs.reward_kwargs.hand_close_target=0.92"
  "++env.task_kwargs.reward_kwargs.hand_open_penalty_scale=10.0"
  "++env.task_kwargs.reward_kwargs.hand_synergy_reward_scale=2.0"
  "++env.task_kwargs.reward_kwargs.hand_synergy_penalty_scale=0.25"
  "++env.task_kwargs.reward_kwargs.hand_synergy_balance_penalty_scale=0.45"
  "++env.task_kwargs.reward_kwargs.lift_bonus_thresh=0.004"
  "++env.task_kwargs.reward_kwargs.lift_bonus_mag=24.0"
  "++env.task_kwargs.reward_kwargs.lift_reward_scale=260.0"
  "++env.task_kwargs.reward_kwargs.lift_reward_cap=0.12"
  "++env.task_kwargs.reward_kwargs.object_xy_drift_free_thresh=0.026"
  "++env.task_kwargs.reward_kwargs.object_xy_drift_penalty_scale=8.0"
  "++env.task_kwargs.reward_kwargs.object_tilt_free_thresh=0.32"
  "++env.task_kwargs.reward_kwargs.object_tilt_penalty_scale=4.0"
  "++env.task_kwargs.reward_kwargs.object_speed_penalty_scale=0.035"
  "++env.task_kwargs.reward_kwargs.object_ang_vel_penalty_scale=0.022"
  "++env.task_kwargs.reward_kwargs.unstable_push_penalty_scale=7.0"
  "++env.task_kwargs.reward_kwargs.bad_push_done=False"
  "agent.params.best_metric=eval/mean_obj_lift"
  "agent.params.degrade_metric=eval/mean_obj_lift"
  "agent.params.curriculum_stage2_metric=eval/mean_obj_lift"
  "agent.params.curriculum_stage2_threshold=0.004"
  "agent.params.rollback_to_best_on_degrade=False"
  "agent.params.eval_deterministic=False"
  "agent.params.rollout_action_noise_std=0.016"
  "agent.params.learning_rate=2.5e-6"
  "agent.params.clip_range=0.10"
  "agent.params.log_ratio_scale=0.40"
  "agent.params.cfm_diff_clip=2.2"
)

export EXTRA_OVERRIDES="${OVERRIDES[*]}"

cd "${REPO}"
exec bash scripts/local/rm75_active6_rfpo_train.sh
