#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${SCRIPT_DIR}/../.." && pwd)"
VENV="${VIVIDEX_VENV:-${REPO}/.venv-vividex}"
PYTHON="${VENV}/bin/python"
SEQ="${SEQ:-ycb-006_mustard_bottle-20200709-subject-01-20200709_143211}"
STAMP="${RUN_TAG:-$(date +%Y%m%d_%H%M%S)}"
RUN_NAME="${RUN_NAME:-rm75_driven12_rfpo_${STAMP}}"
RUN_ROOT="${VIVIDEX_LOCAL_RUN_ROOT:-${REPO}/.local_runs}"
RUN_DIR="${RUN_DIR:-${RUN_ROOT}/${RUN_NAME}}"
DRIVEN12_URDF="${DRIVEN12_URDF:-${REPO}/assets/robot/rm75_inspire_right/urdf/rm75_inspire_hand_right_driven12_nocyl.urdf}"
DRIVEN12_PROFILE="${DRIVEN12_PROFILE:-grasp_first}"
if [[ -z "${TRAJ_SUBDIR:-}" ]]; then
  case "${DRIVEN12_PROFILE}" in
    wrap_lift)
      TRAJ_SUBDIR="rm75_inspire_right_driven12_search_v35offset"
      ;;
    *)
      TRAJ_SUBDIR="rm75_inspire_right_driven12_searchbest"
      ;;
  esac
fi
TRAJ_PATH="${REPO}/norm_trajectories/${TRAJ_SUBDIR}/${SEQ}.npz"

if [[ ! -x "${PYTHON}" ]]; then
  echo "Missing Python env: ${PYTHON}" >&2
  echo "Run scripts/local/setup_vividex_venv.sh first." >&2
  exit 1
fi

cd "${REPO}"
mkdir -p "${RUN_ROOT}" "${RUN_DIR}" "$(dirname "${TRAJ_PATH}")"

export PYTHONPATH="${REPO}${PYTHONPATH:+:${PYTHONPATH}}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export VIVIDEX_HEADLESS_NO_RENDER="${VIVIDEX_HEADLESS_NO_RENDER:-1}"
export VIVIDEX_RM75_URDF_OVERRIDE="${DRIVEN12_URDF}"
export VIVIDEX_RM75_TRAJ_SUBDIR="${TRAJ_SUBDIR}"

if [[ ! -f "${TRAJ_PATH}" || "${REGENERATE_TRAJ:-0}" == "1" ]]; then
  "${PYTHON}" tools/retarget_rm75_inspire_reference.py \
    --src "norm_trajectories/${SEQ}.npz" \
    --dst "${TRAJ_PATH}" \
    --hand-dof 12 \
    --mode reachable \
    --palm-offset 0.057 -0.109 0.070 \
    --overwrite
fi

if [[ "${SKIP_PREFLIGHT:-0}" != "1" ]]; then
  "${PYTHON}" tools/check_rm75_active6_setup.py \
    --seq-name "${SEQ}" \
    --robot-name rm75_inspire_right \
    --norm-traj \
    --profile driven12
fi

N_ENVS="${N_ENVS:-8}"
N_EVAL_ENVS="${N_EVAL_ENVS:-2}"
TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-800000}"
EVAL_FREQ="${EVAL_FREQ:-50000}"
EVAL_N_EPISODES="${EVAL_N_EPISODES:-12}"
SAVE_FREQ="${SAVE_FREQ:-100000}"
RESTORE_FREQ="${RESTORE_FREQ:-100000}"
MULTI_PROC="${MULTI_PROC:-True}"
N_STEPS="${N_STEPS:-2048}"
BATCH_SIZE="${BATCH_SIZE:-512}"
N_EPOCHS="${N_EPOCHS:-4}"
N_SAMPLES="${N_SAMPLES:-16}"
ACTOR_DIMS="${ACTOR_DIMS:-[512,512]}"
CRITIC_DIMS="${CRITIC_DIMS:-[512,512]}"
RESIDUAL_DIMS="${RESIDUAL_DIMS:-[128,64]}"

if [[ "${SMOKE:-0}" == "1" ]]; then
  N_ENVS="${SMOKE_N_ENVS:-1}"
  N_EVAL_ENVS="${SMOKE_N_EVAL_ENVS:-1}"
  TOTAL_TIMESTEPS="${SMOKE_TOTAL_TIMESTEPS:-32}"
  EVAL_FREQ="${SMOKE_EVAL_FREQ:-64}"
  EVAL_N_EPISODES="${SMOKE_EVAL_N_EPISODES:-1}"
  SAVE_FREQ="${SMOKE_SAVE_FREQ:-64}"
  RESTORE_FREQ="${SMOKE_RESTORE_FREQ:-64}"
  MULTI_PROC=False
  N_STEPS="${SMOKE_N_STEPS:-8}"
  BATCH_SIZE="${SMOKE_BATCH_SIZE:-8}"
  N_EPOCHS="${SMOKE_N_EPOCHS:-1}"
  N_SAMPLES="${SMOKE_N_SAMPLES:-2}"
  ACTOR_DIMS="${SMOKE_ACTOR_DIMS:-[64,64]}"
  CRITIC_DIMS="${SMOKE_CRITIC_DIMS:-[64,64]}"
  RESIDUAL_DIMS="${SMOKE_RESIDUAL_DIMS:-[32,32]}"
fi

INFO_KEYS="[pregrasp_success,pregrasp_steps,imitate_steps,hand_jpos_err,obj_com_err,obj_rot_err,obj_lift,contact_count,stable_grasp_contact,thumb_contact,non_thumb_contact_count,palm_contact,stable_contact_hold_steps,rm75_grasp_score,rm75_precision_score,rm75_task_score,fingertip_obj_dist,min_fingertip_obj_dist,palm_obj_dist,hand_close_fraction,hand_thumb_close_fraction,hand_main_close_fraction,hand_pinky_close_fraction,reference_close_fraction,hand_reference_close_error,pregrasp_safe_active,effective_arm_action_scale,effective_hand_action_scale,project_to_object_active,post_stable_lift_only_active,post_contact_lift_assist_active,post_contact_wrist_bias_active,lift_latch_steps_left,done_on_norm_success_10_active,dynamic_close_alpha,dynamic_close_thumb_alpha,dynamic_close_main_alpha,dynamic_close_pinky_alpha,contact_hold_steps,contact_success,lift_success_5cm,norm_success_3,norm_success_10,object_xy_drift,object_speed,object_tilt_err,object_ang_speed,hand_mjpos_err,stage,control_error,obj_tgt_dist]"

CMD=(
  "${PYTHON}" tools/train.py
  agent=fpo
  "agent.multi_proc=${MULTI_PROC}"
  "env.name=${SEQ}"
  "env.robot_name=rm75_inspire_right"
  "env.norm_traj=True"
  "+env.task_kwargs.rm75_pregrasp_safe_action=True"
  "+env.task_kwargs.rm75_pregrasp_safe_margin_steps=0"
  "+env.task_kwargs.rm75_pregrasp_arm_action_scale=0.0"
  "+env.task_kwargs.rm75_pregrasp_hand_action_scale=0.0"
  "+env.task_kwargs.rm75_pregrasp_hand_close_bias=0.0"
  "+env.task_kwargs.rm75_pregrasp_zero_hand_action=True"
  "+env.task_kwargs.rm75_arm_action_scale=0.150"
  "+env.task_kwargs.rm75_hand_action_scale=1.0"
  "+env.task_kwargs.rm75_post_pregrasp_arm_ramp_steps=24"
  "+env.task_kwargs.rm75_post_pregrasp_arm_scale_start=0.008"
  "+env.task_kwargs.rm75_post_pregrasp_arm_scale_end=0.150"
  "+env.task_kwargs.rm75_post_pregrasp_hold_until_stable=True"
  "+env.task_kwargs.rm75_post_pregrasp_hold_arm_scale=0.028"
  "+env.task_kwargs.rm75_post_pregrasp_required_stable_hold_steps=5"
  "+env.task_kwargs.rm75_post_pregrasp_project_to_object=True"
  "+env.task_kwargs.rm75_post_pregrasp_project_until_stable=True"
  "+env.task_kwargs.rm75_post_pregrasp_project_tangent_scale=0.12"
  "+env.task_kwargs.rm75_post_pregrasp_project_max_approach_speed=0.045"
  "+env.task_kwargs.rm75_post_pregrasp_project_max_retreat_speed=0.008"
  "+env.task_kwargs.rm75_default_approach_delta=[0.0,-0.035,0.0]"
  "+env.task_kwargs.rm75_post_stable_lift_only=True"
  "+env.task_kwargs.rm75_post_stable_max_xy_speed=0.008"
  "+env.task_kwargs.rm75_post_stable_max_down_speed=0.002"
  "+env.task_kwargs.rm75_post_stable_max_up_speed=0.026"
  "+env.task_kwargs.rm75_post_stable_lift_bias=0.005"
  "+env.task_kwargs.rm75_post_stable_max_angular_speed=0.10"
  "+env.task_kwargs.rm75_post_contact_lift_assist=False"
  "+env.task_kwargs.rm75_post_contact_lift_min_hold_steps=2"
  "+env.task_kwargs.rm75_post_contact_lift_min_non_thumb_contacts=1"
  "+env.task_kwargs.rm75_post_contact_lift_requires_thumb=True"
  "+env.task_kwargs.rm75_post_contact_max_xy_speed=0.010"
  "+env.task_kwargs.rm75_post_contact_max_down_speed=0.002"
  "+env.task_kwargs.rm75_post_contact_max_up_speed=0.030"
  "+env.task_kwargs.rm75_post_contact_lift_bias=0.0"
  "+env.task_kwargs.rm75_post_contact_max_angular_speed=0.10"
  "+env.task_kwargs.rm75_wrist_angular_bias=[0.0,0.0,0.0]"
  "+env.task_kwargs.rm75_hand_close_bias=0.016"
  "+env.task_kwargs.rm75_hand_close_palm_dist=0.245"
  "+env.task_kwargs.rm75_hand_close_min_finger_dist=0.135"
  "+env.task_kwargs.rm75_hand_dynamic_close_bias=0.72"
  "+env.task_kwargs.rm75_hand_dynamic_close_start=0.250"
  "+env.task_kwargs.rm75_hand_dynamic_close_full=0.080"
  "+env.task_kwargs.rm75_hand_dynamic_close_requires_contact=False"
  "+env.task_kwargs.rm75_hand_dynamic_close_gate_mode=envelope"
  "+env.task_kwargs.rm75_hand_dynamic_close_warmup_steps=4"
  "+env.task_kwargs.rm75_hand_dynamic_close_ramp_steps=20"
  "+env.task_kwargs.rm75_hand_dynamic_close_alpha_smooth=0.50"
  "+env.task_kwargs.rm75_hand_dynamic_close_drift_gate=0.026"
  "+env.task_kwargs.rm75_hand_dynamic_close_contact_hold_steps=2"
  "+env.task_kwargs.rm75_hand_dynamic_close_contact_lock_alpha=0.88"
  "+env.task_kwargs.rm75_hand_dynamic_close_contact_boost=0.55"
  "+env.task_kwargs.rm75_hand_dynamic_close_phase_weight=0.45"
  "+env.task_kwargs.rm75_hand_dynamic_close_phase_start=2"
  "+env.task_kwargs.rm75_hand_dynamic_close_phase_ramp=24"
  "+env.task_kwargs.rm75_hand_dynamic_close_phase_near_gate=0.250"
  "+env.task_kwargs.rm75_hand_dynamic_close_group_mode=ratio"
  "+env.task_kwargs.rm75_hand_dynamic_close_thumb_ratio=0.85"
  "+env.task_kwargs.rm75_hand_dynamic_close_pinky_ratio=0.85"
  "+env.task_kwargs.rm75_hand_dynamic_close_finger_mode=mean"
  "+env.task_kwargs.rm75_hand_precontact_close_cap=0.50"
  "+env.task_kwargs.rm75_hand_precontact_thumb_cap=0.32"
  "+env.task_kwargs.rm75_hand_precontact_pinky_cap=0.42"
  "+env.task_kwargs.rm75_hand_close_bias_weights=[0.36,0.46,1.0,1.0,0.98,0.70]"
  "env.info_keywords=${INFO_KEYS}"
  "+env.task_kwargs.reward_kwargs.pregrasp_success_thresh=0.075"
  "+env.task_kwargs.reward_kwargs.obj_com_done_thresh=0.155"
  "+env.task_kwargs.reward_kwargs.no_contact_grace_steps=10"
  "+env.task_kwargs.reward_kwargs.controller_penalty_scale=950.0"
  "+env.task_kwargs.reward_kwargs.action_penalty_scale=0.010"
  "+env.task_kwargs.reward_kwargs.reward_divisor=10.0"
  "+env.task_kwargs.reward_kwargs.finger_approach_reward_scale=0.90"
  "+env.task_kwargs.reward_kwargs.finger_approach_scale=20.0"
  "+env.task_kwargs.reward_kwargs.min_finger_approach_reward_scale=0.80"
  "+env.task_kwargs.reward_kwargs.min_finger_approach_scale=14.0"
  "+env.task_kwargs.reward_kwargs.palm_approach_reward_scale=0.55"
  "+env.task_kwargs.reward_kwargs.palm_approach_scale=7.0"
  "+env.task_kwargs.reward_kwargs.contact_reward_scale=0.55"
  "+env.task_kwargs.reward_kwargs.thumb_contact_reward_scale=1.60"
  "+env.task_kwargs.reward_kwargs.non_thumb_contact_reward_scale=1.15"
  "+env.task_kwargs.reward_kwargs.required_non_thumb_contacts=1"
  "+env.task_kwargs.reward_kwargs.object_reward_requires_contact=True"
  "+env.task_kwargs.reward_kwargs.object_reward_requires_stable_contact=True"
  "+env.task_kwargs.reward_kwargs.object_reward_contact_hold_steps=5"
  "+env.task_kwargs.reward_kwargs.no_contact_penalty=0.25"
  "env.task_kwargs.reward_kwargs.object_reward_scale=8.0"
  "env.task_kwargs.reward_kwargs.obj_err_scale=50.0"
  "+env.task_kwargs.reward_kwargs.obj_rot_term=0.1"
  "+env.task_kwargs.reward_kwargs.hand_mimic_reward_scale=2.2"
  "+env.task_kwargs.reward_kwargs.hand_mimic_scale=10.0"
  "+env.task_kwargs.reward_kwargs.hand_close_reward_scale=2.5"
  "+env.task_kwargs.reward_kwargs.hand_close_near_dist=0.120"
  "+env.task_kwargs.reward_kwargs.hand_close_palm_near_dist=0.235"
  "+env.task_kwargs.reward_kwargs.hand_close_min_finger_near_dist=0.125"
  "+env.task_kwargs.reward_kwargs.hand_close_contact_only=False"
  "+env.task_kwargs.reward_kwargs.hand_close_target=0.68"
  "+env.task_kwargs.reward_kwargs.hand_open_penalty_scale=1.2"
  "+env.task_kwargs.reward_kwargs.reference_close_reward_scale=0.80"
  "+env.task_kwargs.reward_kwargs.reference_close_penalty_scale=1.00"
  "+env.task_kwargs.reward_kwargs.reference_close_tolerance=0.12"
  "+env.task_kwargs.reward_kwargs.reference_close_start_step=4"
  "+env.task_kwargs.reward_kwargs.early_close_penalty_scale=1.20"
  "+env.task_kwargs.reward_kwargs.early_close_palm_dist=0.220"
  "+env.task_kwargs.reward_kwargs.early_close_min_finger_dist=0.125"
  "+env.task_kwargs.reward_kwargs.hand_synergy_reward_scale=1.2"
  "+env.task_kwargs.reward_kwargs.hand_synergy_penalty_scale=0.70"
  "+env.task_kwargs.reward_kwargs.hand_synergy_balance_penalty_scale=0.70"
  "+env.task_kwargs.reward_kwargs.hand_synergy_min_main_close=0.18"
  "+env.task_kwargs.reward_kwargs.hand_synergy_thumb_target_ratio=0.85"
  "+env.task_kwargs.reward_kwargs.hand_synergy_pinky_target_ratio=0.85"
  "+env.task_kwargs.reward_kwargs.stable_contact_bonus=10.0"
  "+env.task_kwargs.reward_kwargs.contact_hold_bonus_scale=5.5"
  "+env.task_kwargs.reward_kwargs.contact_hold_bonus_steps=7"
  "env.task_kwargs.reward_kwargs.lift_bonus_thresh=0.008"
  "env.task_kwargs.reward_kwargs.lift_bonus_mag=7.0"
  "+env.task_kwargs.reward_kwargs.lift_reward_scale=50.0"
  "+env.task_kwargs.reward_kwargs.lift_reward_cap=0.08"
  "+env.task_kwargs.reward_kwargs.object_xy_drift_free_thresh=0.012"
  "+env.task_kwargs.reward_kwargs.object_xy_drift_penalty_scale=26.0"
  "+env.task_kwargs.reward_kwargs.object_speed_penalty_scale=0.060"
  "+env.task_kwargs.reward_kwargs.object_tilt_free_thresh=0.20"
  "+env.task_kwargs.reward_kwargs.object_tilt_penalty_scale=8.0"
  "+env.task_kwargs.reward_kwargs.object_ang_vel_penalty_scale=0.040"
  "+env.task_kwargs.reward_kwargs.unstable_push_penalty_scale=18.0"
  "+env.task_kwargs.reward_kwargs.bad_push_done=True"
  "+env.task_kwargs.reward_kwargs.bad_push_min_step=8"
  "+env.task_kwargs.reward_kwargs.bad_push_drift_thresh=0.050"
  "+env.task_kwargs.reward_kwargs.bad_push_tilt_thresh=0.36"
  "agent.params.actor_objective=fpo"
  "agent.params.trust_region_mode=aspo"
  "agent.params.learning_rate=5.0e-6"
  "agent.params.clip_range=0.10"
  "agent.params.log_ratio_scale=0.50"
  "agent.params.cfm_diff_clip=2.0"
  "agent.params.cfm_loss_clamp=20.0"
  "agent.params.action_head_mode=flow_residual"
  "agent.params.rollout_action_noise_std=0.010"
  "agent.params.rollout_deterministic=False"
  "agent.params.eval_deterministic=False"
  "agent.params.n_steps=${N_STEPS}"
  "agent.params.batch_size=${BATCH_SIZE}"
  "agent.params.n_epochs=${N_EPOCHS}"
  "agent.params.n_samples_per_action=${N_SAMPLES}"
  "agent.params.sampling_steps=8"
  "agent.params.actor_hidden_dims=${ACTOR_DIMS}"
  "agent.params.critic_hidden_dims=${CRITIC_DIMS}"
  "agent.params.residual_head_hidden_dims=${RESIDUAL_DIMS}"
  "agent.params.activation=elu"
  "agent.params.max_grad_norm=1.0"
  "agent.params.actor_max_grad_norm=0.5"
  "agent.params.critic_max_grad_norm=2.0"
  "agent.params.curriculum_pregrasp_threshold=0.95"
  "agent.params.curriculum_stage2_metric=eval/mean_stable_grasp_contact"
  "agent.params.curriculum_stage2_threshold=0.04"
  "agent.params.best_metric=eval/mean_rm75_task_score"
  "agent.params.degrade_metric=eval/mean_rm75_task_score"
  "agent.params.save_best_model=True"
  "agent.params.rollback_to_best_on_degrade=True"
  "agent.params.rollback_patience=4"
  "agent.params.degrade_threshold=5.0"
  "n_envs=${N_ENVS}"
  "n_eval_envs=${N_EVAL_ENVS}"
  "eval_n_episodes=${EVAL_N_EPISODES}"
  "total_timesteps=${TOTAL_TIMESTEPS}"
  "eval_freq=${EVAL_FREQ}"
  "save_freq=${SAVE_FREQ}"
  "restore_checkpoint_freq=${RESTORE_FREQ}"
  "wandb.project=${WANDB_PROJECT:-vividex_rm75_driven12}"
  "wandb.group=${WANDB_GROUP:-rm75_driven12_rfpo}"
  "wandb.sweep_name_prefix=${RUN_NAME}"
  "hydra.run.dir=${RUN_DIR}"
)

PROFILE_OVERRIDES=()
case "${DRIVEN12_PROFILE}" in
  conservative|stable_first|hold_first)
    ;;
  wrap_lift)
    PROFILE_OVERRIDES=(
      "+env.task_kwargs.rm75_min_imitate_steps=80"
      "env.task_kwargs.rm75_default_approach_delta=[0.0,-0.035,0.0]"
      "env.task_kwargs.rm75_arm_action_scale=0.235"
      "env.task_kwargs.rm75_post_pregrasp_arm_ramp_steps=10"
      "env.task_kwargs.rm75_post_pregrasp_arm_scale_start=0.020"
      "env.task_kwargs.rm75_post_pregrasp_arm_scale_end=0.235"
      "env.task_kwargs.rm75_post_pregrasp_hold_until_stable=True"
      "env.task_kwargs.rm75_post_pregrasp_hold_arm_scale=0.018"
      "env.task_kwargs.rm75_post_pregrasp_required_stable_hold_steps=3"
      "env.task_kwargs.rm75_post_pregrasp_project_to_object=True"
      "env.task_kwargs.rm75_post_pregrasp_project_until_stable=True"
      "env.task_kwargs.rm75_post_pregrasp_project_tangent_scale=0.10"
      "env.task_kwargs.rm75_post_pregrasp_project_max_approach_speed=0.050"
      "env.task_kwargs.rm75_post_pregrasp_project_max_retreat_speed=0.008"
      "env.task_kwargs.rm75_post_stable_lift_only=True"
      "env.task_kwargs.rm75_post_stable_max_xy_speed=0.006"
      "env.task_kwargs.rm75_post_stable_max_down_speed=0.001"
      "env.task_kwargs.rm75_post_stable_max_up_speed=0.052"
      "env.task_kwargs.rm75_post_stable_lift_bias=0.010"
      "env.task_kwargs.rm75_post_stable_max_angular_speed=0.10"
      "env.task_kwargs.rm75_post_contact_lift_assist=True"
      "env.task_kwargs.rm75_post_contact_lift_min_hold_steps=2"
      "env.task_kwargs.rm75_post_contact_lift_min_non_thumb_contacts=1"
      "env.task_kwargs.rm75_post_contact_lift_requires_thumb=True"
      "env.task_kwargs.rm75_post_contact_max_xy_speed=0.006"
      "env.task_kwargs.rm75_post_contact_max_down_speed=0.001"
      "env.task_kwargs.rm75_post_contact_max_up_speed=0.044"
      "env.task_kwargs.rm75_post_contact_lift_bias=0.006"
      "env.task_kwargs.rm75_post_contact_max_angular_speed=0.10"
      "env.task_kwargs.rm75_hand_close_bias=0.026"
      "env.task_kwargs.rm75_hand_close_palm_dist=0.325"
      "env.task_kwargs.rm75_hand_close_min_finger_dist=0.175"
      "env.task_kwargs.rm75_hand_dynamic_close_bias=1.15"
      "env.task_kwargs.rm75_hand_dynamic_close_start=0.335"
      "env.task_kwargs.rm75_hand_dynamic_close_full=0.100"
      "env.task_kwargs.rm75_hand_dynamic_close_requires_contact=False"
      "env.task_kwargs.rm75_hand_dynamic_close_gate_mode=blend"
      "++env.task_kwargs.rm75_hand_dynamic_close_palm_weight=0.70"
      "++env.task_kwargs.rm75_hand_dynamic_close_finger_weight=0.30"
      "env.task_kwargs.rm75_hand_dynamic_close_warmup_steps=0"
      "env.task_kwargs.rm75_hand_dynamic_close_ramp_steps=9"
      "env.task_kwargs.rm75_hand_dynamic_close_alpha_smooth=0.18"
      "env.task_kwargs.rm75_hand_dynamic_close_drift_gate=0.060"
      "env.task_kwargs.rm75_hand_dynamic_close_contact_hold_steps=1"
      "env.task_kwargs.rm75_hand_dynamic_close_contact_lock_alpha=1.0"
      "env.task_kwargs.rm75_hand_dynamic_close_contact_boost=0.92"
      "env.task_kwargs.rm75_hand_dynamic_close_phase_weight=0.75"
      "env.task_kwargs.rm75_hand_dynamic_close_phase_start=0"
      "env.task_kwargs.rm75_hand_dynamic_close_phase_ramp=8"
      "env.task_kwargs.rm75_hand_dynamic_close_phase_near_gate=0.335"
      "env.task_kwargs.rm75_hand_dynamic_close_group_mode=ratio"
      "env.task_kwargs.rm75_hand_dynamic_close_thumb_ratio=0.95"
      "env.task_kwargs.rm75_hand_dynamic_close_pinky_ratio=0.95"
      "env.task_kwargs.rm75_hand_precontact_close_cap=0.76"
      "env.task_kwargs.rm75_hand_precontact_thumb_cap=0.68"
      "env.task_kwargs.rm75_hand_precontact_pinky_cap=0.68"
      "env.task_kwargs.rm75_hand_close_bias_weights=[0.96,0.98,1.10,1.10,1.08,1.02]"
      "env.task_kwargs.reward_kwargs.obj_com_done_thresh=0.280"
      "env.task_kwargs.reward_kwargs.no_contact_grace_steps=34"
      "env.task_kwargs.reward_kwargs.required_non_thumb_contacts=1"
      "env.task_kwargs.reward_kwargs.contact_reward_scale=0.30"
      "env.task_kwargs.reward_kwargs.thumb_contact_reward_scale=3.0"
      "env.task_kwargs.reward_kwargs.non_thumb_contact_reward_scale=3.2"
      "env.task_kwargs.reward_kwargs.object_reward_requires_contact=True"
      "env.task_kwargs.reward_kwargs.object_reward_requires_stable_contact=False"
      "env.task_kwargs.reward_kwargs.object_reward_contact_hold_steps=2"
      "env.task_kwargs.reward_kwargs.no_contact_penalty=0.16"
      "env.task_kwargs.reward_kwargs.object_reward_scale=8.0"
      "env.task_kwargs.reward_kwargs.obj_err_scale=28.0"
      "env.task_kwargs.reward_kwargs.hand_close_reward_scale=12.0"
      "env.task_kwargs.reward_kwargs.hand_close_target=0.92"
      "env.task_kwargs.reward_kwargs.hand_open_penalty_scale=13.0"
      "env.task_kwargs.reward_kwargs.early_close_penalty_scale=0.15"
      "env.task_kwargs.reward_kwargs.hand_synergy_reward_scale=2.3"
      "env.task_kwargs.reward_kwargs.hand_synergy_penalty_scale=0.25"
      "env.task_kwargs.reward_kwargs.hand_synergy_balance_penalty_scale=0.50"
      "env.task_kwargs.reward_kwargs.hand_synergy_thumb_target_ratio=0.95"
      "env.task_kwargs.reward_kwargs.hand_synergy_pinky_target_ratio=0.95"
      "env.task_kwargs.reward_kwargs.stable_contact_bonus=20.0"
      "env.task_kwargs.reward_kwargs.contact_hold_bonus_scale=12.0"
      "env.task_kwargs.reward_kwargs.contact_hold_bonus_steps=10"
      "env.task_kwargs.reward_kwargs.lift_bonus_thresh=0.006"
      "env.task_kwargs.reward_kwargs.lift_bonus_mag=24.0"
      "env.task_kwargs.reward_kwargs.lift_reward_scale=260.0"
      "env.task_kwargs.reward_kwargs.lift_reward_cap=0.13"
      "env.task_kwargs.reward_kwargs.object_xy_drift_free_thresh=0.035"
      "env.task_kwargs.reward_kwargs.object_xy_drift_penalty_scale=7.5"
      "env.task_kwargs.reward_kwargs.object_tilt_free_thresh=0.34"
      "env.task_kwargs.reward_kwargs.object_tilt_penalty_scale=3.5"
      "env.task_kwargs.reward_kwargs.object_speed_penalty_scale=0.030"
      "env.task_kwargs.reward_kwargs.object_ang_vel_penalty_scale=0.020"
      "env.task_kwargs.reward_kwargs.unstable_push_penalty_scale=9.0"
      "env.task_kwargs.reward_kwargs.bad_push_done=False"
      "agent.params.learning_rate=2.0e-6"
      "agent.params.min_learning_rate=2.0e-6"
      "agent.params.max_learning_rate=2.0e-6"
      "agent.params.log_ratio_scale=0.40"
      "agent.params.rollout_action_noise_std=0.012"
      "agent.params.residual_action_scale=0.055"
      "agent.params.curriculum_stage2_metric=eval/mean_stable_grasp_contact"
      "agent.params.curriculum_stage2_threshold=0.08"
      "agent.params.best_metric=eval/mean_rm75_task_score"
      "agent.params.degrade_metric=eval/mean_rm75_task_score"
      "agent.params.rollback_to_best_on_degrade=True"
      "agent.params.rollback_patience=4"
      "agent.params.degrade_threshold=0.25"
    )
    ;;
  grasp_first|score_first)
    PROFILE_OVERRIDES=(
      "env.task_kwargs.rm75_arm_action_scale=0.205"
      "env.task_kwargs.rm75_post_pregrasp_arm_ramp_steps=12"
      "env.task_kwargs.rm75_post_pregrasp_arm_scale_start=0.020"
      "env.task_kwargs.rm75_post_pregrasp_arm_scale_end=0.205"
      "env.task_kwargs.rm75_post_pregrasp_hold_until_stable=True"
      "env.task_kwargs.rm75_post_pregrasp_hold_arm_scale=0.020"
      "env.task_kwargs.rm75_post_pregrasp_required_stable_hold_steps=2"
      "env.task_kwargs.rm75_post_pregrasp_project_tangent_scale=0.18"
      "env.task_kwargs.rm75_post_pregrasp_project_max_approach_speed=0.055"
      "env.task_kwargs.rm75_post_pregrasp_project_max_retreat_speed=0.012"
      "env.task_kwargs.rm75_post_contact_lift_assist=True"
      "env.task_kwargs.rm75_post_contact_lift_min_hold_steps=1"
      "env.task_kwargs.rm75_post_contact_lift_min_non_thumb_contacts=1"
      "env.task_kwargs.rm75_post_contact_lift_requires_thumb=False"
      "env.task_kwargs.rm75_post_contact_max_xy_speed=0.008"
      "env.task_kwargs.rm75_post_contact_max_down_speed=0.001"
      "env.task_kwargs.rm75_post_contact_max_up_speed=0.060"
      "env.task_kwargs.rm75_post_contact_lift_bias=0.012"
      "env.task_kwargs.rm75_post_contact_max_angular_speed=0.16"
      "env.task_kwargs.rm75_hand_close_bias=0.030"
      "env.task_kwargs.rm75_hand_close_palm_dist=0.255"
      "env.task_kwargs.rm75_hand_close_min_finger_dist=0.135"
      "env.task_kwargs.rm75_hand_dynamic_close_bias=0.95"
      "env.task_kwargs.rm75_hand_dynamic_close_start=0.300"
      "env.task_kwargs.rm75_hand_dynamic_close_full=0.085"
      "env.task_kwargs.rm75_hand_dynamic_close_requires_contact=False"
      "env.task_kwargs.rm75_hand_dynamic_close_gate_mode=blend"
      "++env.task_kwargs.rm75_hand_dynamic_close_palm_weight=0.70"
      "++env.task_kwargs.rm75_hand_dynamic_close_finger_weight=0.30"
      "env.task_kwargs.rm75_hand_dynamic_close_warmup_steps=0"
      "env.task_kwargs.rm75_hand_dynamic_close_ramp_steps=10"
      "env.task_kwargs.rm75_hand_dynamic_close_alpha_smooth=0.16"
      "env.task_kwargs.rm75_hand_dynamic_close_drift_gate=0.040"
      "env.task_kwargs.rm75_hand_dynamic_close_contact_hold_steps=1"
      "env.task_kwargs.rm75_hand_dynamic_close_contact_lock_alpha=1.0"
      "env.task_kwargs.rm75_hand_dynamic_close_contact_boost=0.85"
      "env.task_kwargs.rm75_hand_dynamic_close_phase_weight=0.65"
      "env.task_kwargs.rm75_hand_dynamic_close_phase_start=0"
      "env.task_kwargs.rm75_hand_dynamic_close_phase_ramp=10"
      "env.task_kwargs.rm75_hand_dynamic_close_phase_near_gate=0.300"
      "env.task_kwargs.rm75_hand_dynamic_close_group_mode=ratio"
      "env.task_kwargs.rm75_hand_dynamic_close_thumb_ratio=0.95"
      "env.task_kwargs.rm75_hand_dynamic_close_pinky_ratio=0.95"
      "env.task_kwargs.rm75_hand_precontact_close_cap=0.72"
      "env.task_kwargs.rm75_hand_precontact_thumb_cap=0.60"
      "env.task_kwargs.rm75_hand_precontact_pinky_cap=0.62"
      "env.task_kwargs.rm75_hand_close_bias_weights=[0.88,0.95,1.08,1.08,1.06,0.98]"
      "env.task_kwargs.reward_kwargs.obj_com_done_thresh=0.240"
      "env.task_kwargs.reward_kwargs.no_contact_grace_steps=48"
      "env.task_kwargs.reward_kwargs.required_non_thumb_contacts=1"
      "env.task_kwargs.reward_kwargs.contact_reward_scale=0.35"
      "env.task_kwargs.reward_kwargs.thumb_contact_reward_scale=2.2"
      "env.task_kwargs.reward_kwargs.non_thumb_contact_reward_scale=2.6"
      "env.task_kwargs.reward_kwargs.object_reward_requires_contact=True"
      "env.task_kwargs.reward_kwargs.object_reward_requires_stable_contact=False"
      "env.task_kwargs.reward_kwargs.object_reward_contact_hold_steps=1"
      "env.task_kwargs.reward_kwargs.no_contact_penalty=0.08"
      "env.task_kwargs.reward_kwargs.object_reward_scale=7.5"
      "env.task_kwargs.reward_kwargs.obj_err_scale=32.0"
      "env.task_kwargs.reward_kwargs.hand_close_reward_scale=10.0"
      "env.task_kwargs.reward_kwargs.hand_close_target=0.88"
      "env.task_kwargs.reward_kwargs.hand_open_penalty_scale=7.0"
      "env.task_kwargs.reward_kwargs.reference_close_reward_scale=1.2"
      "env.task_kwargs.reward_kwargs.reference_close_penalty_scale=1.0"
      "env.task_kwargs.reward_kwargs.early_close_penalty_scale=0.35"
      "env.task_kwargs.reward_kwargs.hand_synergy_reward_scale=1.8"
      "env.task_kwargs.reward_kwargs.hand_synergy_penalty_scale=0.30"
      "env.task_kwargs.reward_kwargs.hand_synergy_balance_penalty_scale=0.45"
      "env.task_kwargs.reward_kwargs.hand_synergy_thumb_target_ratio=0.95"
      "env.task_kwargs.reward_kwargs.hand_synergy_pinky_target_ratio=0.95"
      "env.task_kwargs.reward_kwargs.stable_contact_bonus=16.0"
      "env.task_kwargs.reward_kwargs.contact_hold_bonus_scale=10.0"
      "env.task_kwargs.reward_kwargs.contact_hold_bonus_steps=8"
      "env.task_kwargs.reward_kwargs.lift_bonus_thresh=0.004"
      "env.task_kwargs.reward_kwargs.lift_bonus_mag=20.0"
      "env.task_kwargs.reward_kwargs.lift_reward_scale=220.0"
      "env.task_kwargs.reward_kwargs.lift_reward_cap=0.12"
      "env.task_kwargs.reward_kwargs.object_xy_drift_free_thresh=0.024"
      "env.task_kwargs.reward_kwargs.object_xy_drift_penalty_scale=10.0"
      "env.task_kwargs.reward_kwargs.object_tilt_free_thresh=0.32"
      "env.task_kwargs.reward_kwargs.object_tilt_penalty_scale=4.5"
      "env.task_kwargs.reward_kwargs.object_speed_penalty_scale=0.040"
      "env.task_kwargs.reward_kwargs.object_ang_vel_penalty_scale=0.024"
      "env.task_kwargs.reward_kwargs.unstable_push_penalty_scale=6.0"
      "env.task_kwargs.reward_kwargs.bad_push_done=False"
      "agent.params.learning_rate=3.0e-6"
      "agent.params.log_ratio_scale=0.40"
      "agent.params.rollout_action_noise_std=0.016"
      "agent.params.residual_action_scale=0.060"
      "agent.params.curriculum_stage2_metric=eval/mean_obj_lift"
      "agent.params.curriculum_stage2_threshold=0.004"
      "agent.params.best_metric=eval/mean_rm75_grasp_score"
      "agent.params.degrade_metric=eval/mean_rm75_grasp_score"
      "agent.params.rollback_to_best_on_degrade=False"
      "agent.params.rollback_patience=0"
    )
    if [[ "${DRIVEN12_PROFILE}" == "score_first" ]]; then
      PROFILE_OVERRIDES+=(
        "+env.task_kwargs.rm75_done_on_norm_success_10=True"
        "+env.task_kwargs.rm75_post_lift_latch_steps=18"
        "+env.task_kwargs.rm75_post_lift_latch_hand_alpha=1.0"
        "env.task_kwargs.rm75_post_pregrasp_required_stable_hold_steps=1"
        "env.task_kwargs.rm75_post_contact_lift_assist=True"
        "env.task_kwargs.rm75_post_contact_lift_min_hold_steps=1"
        "env.task_kwargs.rm75_post_contact_lift_min_non_thumb_contacts=1"
        "env.task_kwargs.rm75_post_contact_lift_requires_thumb=True"
        "env.task_kwargs.rm75_post_contact_max_xy_speed=0.006"
        "env.task_kwargs.rm75_post_contact_max_down_speed=0.0"
        "env.task_kwargs.rm75_post_contact_max_up_speed=0.045"
        "env.task_kwargs.rm75_post_contact_lift_bias=0.010"
        "env.task_kwargs.rm75_post_contact_max_angular_speed=0.08"
        "env.task_kwargs.reward_kwargs.obj_com_done_thresh=0.320"
        "env.task_kwargs.reward_kwargs.no_contact_grace_steps=56"
        "env.task_kwargs.reward_kwargs.lift_bonus_thresh=0.003"
        "env.task_kwargs.reward_kwargs.lift_bonus_mag=28.0"
        "env.task_kwargs.reward_kwargs.lift_reward_scale=300.0"
        "env.task_kwargs.reward_kwargs.lift_reward_cap=0.16"
        "env.task_kwargs.reward_kwargs.object_xy_drift_free_thresh=0.030"
        "env.task_kwargs.reward_kwargs.object_xy_drift_penalty_scale=7.0"
        "env.task_kwargs.reward_kwargs.object_speed_penalty_scale=0.030"
        "env.task_kwargs.reward_kwargs.object_tilt_free_thresh=0.36"
        "env.task_kwargs.reward_kwargs.object_tilt_penalty_scale=3.5"
        "env.task_kwargs.reward_kwargs.object_ang_vel_penalty_scale=0.018"
        "env.task_kwargs.reward_kwargs.unstable_push_penalty_scale=5.0"
        "agent.params.best_metric=eval/mean_norm_success_10"
        "agent.params.degrade_metric=eval/mean_norm_success_10"
        "agent.params.rollback_to_best_on_degrade=False"
        "agent.params.learning_rate=1.5e-6"
        "agent.params.min_learning_rate=1.5e-6"
        "agent.params.max_learning_rate=1.5e-6"
        "agent.params.log_ratio_scale=0.32"
        "agent.params.rollout_action_noise_std=0.010"
        "agent.params.residual_action_scale=0.040"
      )
    fi
    ;;
  *)
    echo "Unknown DRIVEN12_PROFILE=${DRIVEN12_PROFILE}" >&2
    exit 2
    ;;
esac

if [[ ${#PROFILE_OVERRIDES[@]} -gt 0 ]]; then
  CMD+=("${PROFILE_OVERRIDES[@]}")
fi

if [[ -n "${EXTRA_OVERRIDES:-}" ]]; then
  read -r -a EXTRA_OVERRIDE_ARGS <<< "${EXTRA_OVERRIDES}"
  CMD+=("${EXTRA_OVERRIDE_ARGS[@]}")
fi

echo "[driven12-rfpo] profile: ${DRIVEN12_PROFILE}"
printf '[driven12-rfpo] command: %q ' "${CMD[@]}"
printf '\n'
"${CMD[@]}"
