#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${SCRIPT_DIR}/../.." && pwd)"
VENV="${VIVIDEX_VENV:-${REPO}/.venv-vividex}"
PYTHON="${VENV}/bin/python"
SEQ="${SEQ:-ycb-006_mustard_bottle-20200709-subject-01-20200709_143211}"
STAMP="${RUN_TAG:-$(date +%Y%m%d_%H%M%S)}"
RUN_NAME="${RUN_NAME:-rm75_active6_rfpo_${STAMP}}"
RUN_ROOT="${VIVIDEX_LOCAL_RUN_ROOT:-${REPO}/.local_runs}"
RUN_DIR="${RUN_DIR:-${RUN_ROOT}/${RUN_NAME}}"
ACTIVE6_URDF="${ACTIVE6_URDF:-${REPO}/assets/robot/rm75_inspire_right/urdf/rm75_inspire_hand_right_active6.urdf}"

if [[ ! -x "${PYTHON}" ]]; then
  echo "Missing Python env: ${PYTHON}" >&2
  echo "Run scripts/local/setup_vividex_venv.sh first." >&2
  exit 1
fi

cd "${REPO}"
mkdir -p "${RUN_ROOT}" "${RUN_DIR}"

export PYTHONPATH="${REPO}${PYTHONPATH:+:${PYTHONPATH}}"
export WANDB_MODE="${WANDB_MODE:-offline}"
export VIVIDEX_HEADLESS_NO_RENDER="${VIVIDEX_HEADLESS_NO_RENDER:-1}"
export VIVIDEX_RM75_URDF_OVERRIDE="${ACTIVE6_URDF}"

if [[ "${ALLOW_RM75_TRAJ_SUBDIR:-0}" != "1" ]]; then
  unset VIVIDEX_RM75_TRAJ_SUBDIR
fi

if [[ "${SKIP_PREFLIGHT:-0}" != "1" ]]; then
  "${PYTHON}" tools/check_rm75_active6_setup.py \
    --seq-name "${SEQ}" \
    --robot-name rm75_inspire_right \
    --norm-traj
fi

N_ENVS="${N_ENVS:-8}"
N_EVAL_ENVS="${N_EVAL_ENVS:-2}"
TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-800000}"
EVAL_FREQ="${EVAL_FREQ:-50000}"
EVAL_N_EPISODES="${EVAL_N_EPISODES:-12}"
SAVE_FREQ="${SAVE_FREQ:-100000}"
RESTORE_FREQ="${RESTORE_FREQ:-100000}"
MULTI_PROC="${MULTI_PROC:-True}"
N_STEPS="${N_STEPS:-2048}"
BATCH_SIZE="${BATCH_SIZE:-512}"
N_EPOCHS="${N_EPOCHS:-4}"
N_SAMPLES="${N_SAMPLES:-16}"
ACTOR_DIMS="${ACTOR_DIMS:-[512,512]}"
CRITIC_DIMS="${CRITIC_DIMS:-[512,512]}"
RESIDUAL_DIMS="${RESIDUAL_DIMS:-[128,64]}"

if [[ "${SMOKE:-0}" == "1" ]]; then
  N_ENVS="${SMOKE_N_ENVS:-1}"
  N_EVAL_ENVS="${SMOKE_N_EVAL_ENVS:-1}"
  TOTAL_TIMESTEPS="${SMOKE_TOTAL_TIMESTEPS:-32}"
  EVAL_FREQ="${SMOKE_EVAL_FREQ:-64}"
  EVAL_N_EPISODES="${SMOKE_EVAL_N_EPISODES:-1}"
  SAVE_FREQ="${SMOKE_SAVE_FREQ:-64}"
  RESTORE_FREQ="${SMOKE_RESTORE_FREQ:-64}"
  MULTI_PROC=False
  N_STEPS="${SMOKE_N_STEPS:-8}"
  BATCH_SIZE="${SMOKE_BATCH_SIZE:-8}"
  N_EPOCHS="${SMOKE_N_EPOCHS:-1}"
  N_SAMPLES="${SMOKE_N_SAMPLES:-2}"
  ACTOR_DIMS="${SMOKE_ACTOR_DIMS:-[64,64]}"
  CRITIC_DIMS="${SMOKE_CRITIC_DIMS:-[64,64]}"
  RESIDUAL_DIMS="${SMOKE_RESIDUAL_DIMS:-[32,32]}"
fi

INFO_KEYS="[pregrasp_success,pregrasp_steps,imitate_steps,hand_jpos_err,obj_com_err,obj_rot_err,obj_lift,contact_count,stable_grasp_contact,thumb_contact,non_thumb_contact_count,palm_contact,stable_contact_hold_steps,rm75_grasp_score,rm75_precision_score,rm75_task_score,fingertip_obj_dist,min_fingertip_obj_dist,palm_obj_dist,hand_close_fraction,hand_thumb_close_fraction,hand_main_close_fraction,hand_pinky_close_fraction,reference_close_fraction,hand_reference_close_error,pregrasp_safe_active,effective_arm_action_scale,effective_hand_action_scale,project_to_object_active,post_stable_lift_only_active,post_contact_lift_assist_active,post_contact_wrist_bias_active,dynamic_close_alpha,dynamic_close_thumb_alpha,dynamic_close_main_alpha,dynamic_close_pinky_alpha,contact_hold_steps,contact_success,lift_success_5cm,norm_success_3,norm_success_10,object_xy_drift,object_speed,object_tilt_err,object_ang_speed,hand_mjpos_err,stage,control_error,obj_tgt_dist]"

CMD=(
  "${PYTHON}" tools/train.py
  agent=fpo
  "agent.multi_proc=${MULTI_PROC}"
  "env.name=${SEQ}"
  "env.robot_name=rm75_inspire_right"
  "env.norm_traj=True"
  "+env.task_kwargs.rm75_pregrasp_safe_action=True"
  "+env.task_kwargs.rm75_pregrasp_safe_margin_steps=0"
  "+env.task_kwargs.rm75_pregrasp_arm_action_scale=0.0"
  "+env.task_kwargs.rm75_pregrasp_hand_action_scale=0.0"
  "+env.task_kwargs.rm75_pregrasp_hand_close_bias=0.0"
  "+env.task_kwargs.rm75_pregrasp_zero_hand_action=True"
  "+env.task_kwargs.rm75_arm_action_scale=0.20"
  "+env.task_kwargs.rm75_hand_action_scale=1.0"
  "+env.task_kwargs.rm75_post_pregrasp_arm_ramp_steps=18"
  "+env.task_kwargs.rm75_post_pregrasp_arm_scale_start=0.018"
  "+env.task_kwargs.rm75_post_pregrasp_arm_scale_end=0.20"
  "+env.task_kwargs.rm75_post_pregrasp_hold_until_stable=True"
  "+env.task_kwargs.rm75_post_pregrasp_hold_arm_scale=0.030"
  "+env.task_kwargs.rm75_post_pregrasp_required_stable_hold_steps=3"
  "+env.task_kwargs.rm75_post_pregrasp_project_to_object=True"
  "+env.task_kwargs.rm75_post_pregrasp_project_until_stable=True"
  "+env.task_kwargs.rm75_post_pregrasp_project_tangent_scale=0.16"
  "+env.task_kwargs.rm75_post_pregrasp_project_max_approach_speed=0.052"
  "+env.task_kwargs.rm75_post_pregrasp_project_max_retreat_speed=0.010"
  "+env.task_kwargs.rm75_default_approach_delta=[0.0,-0.05,0.0]"
  "+env.task_kwargs.rm75_post_stable_lift_only=True"
  "+env.task_kwargs.rm75_post_stable_max_xy_speed=0.010"
  "+env.task_kwargs.rm75_post_stable_max_down_speed=0.002"
  "+env.task_kwargs.rm75_post_stable_max_up_speed=0.030"
  "+env.task_kwargs.rm75_post_stable_lift_bias=0.005"
  "+env.task_kwargs.rm75_post_stable_max_angular_speed=0.12"
  "+env.task_kwargs.rm75_post_contact_lift_assist=False"
  "+env.task_kwargs.rm75_post_contact_lift_min_hold_steps=1"
  "+env.task_kwargs.rm75_post_contact_lift_min_non_thumb_contacts=0"
  "+env.task_kwargs.rm75_post_contact_lift_requires_thumb=True"
  "+env.task_kwargs.rm75_post_contact_max_xy_speed=0.014"
  "+env.task_kwargs.rm75_post_contact_max_down_speed=0.002"
  "+env.task_kwargs.rm75_post_contact_max_up_speed=0.055"
  "+env.task_kwargs.rm75_post_contact_lift_bias=0.0"
  "+env.task_kwargs.rm75_post_contact_max_angular_speed=0.16"
  "+env.task_kwargs.rm75_post_contact_wrist_bias=[0.0,0.0,0.0]"
  "+env.task_kwargs.rm75_post_contact_wrist_min_hold_steps=1"
  "+env.task_kwargs.rm75_post_contact_wrist_min_non_thumb_contacts=0"
  "+env.task_kwargs.rm75_post_contact_wrist_requires_thumb=True"
  "+env.task_kwargs.rm75_wrist_angular_bias=[0.0,0.0,0.0]"
  "+env.task_kwargs.rm75_wrist_angular_bias_start_step=0"
  "+env.task_kwargs.rm75_wrist_angular_bias_end_step=1000000"
  "+env.task_kwargs.rm75_hand_close_bias=0.018"
  "+env.task_kwargs.rm75_hand_close_palm_dist=0.245"
  "+env.task_kwargs.rm75_hand_close_min_finger_dist=0.130"
  "+env.task_kwargs.rm75_hand_dynamic_close_bias=0.72"
  "+env.task_kwargs.rm75_hand_dynamic_close_start=0.260"
  "+env.task_kwargs.rm75_hand_dynamic_close_full=0.085"
  "+env.task_kwargs.rm75_hand_dynamic_close_requires_contact=False"
  "+env.task_kwargs.rm75_hand_dynamic_close_gate_mode=envelope"
  "+env.task_kwargs.rm75_hand_dynamic_close_warmup_steps=2"
  "+env.task_kwargs.rm75_hand_dynamic_close_ramp_steps=18"
  "+env.task_kwargs.rm75_hand_dynamic_close_alpha_smooth=0.35"
  "+env.task_kwargs.rm75_hand_dynamic_close_drift_gate=0.030"
  "+env.task_kwargs.rm75_hand_dynamic_close_contact_hold_steps=2"
  "+env.task_kwargs.rm75_hand_dynamic_close_contact_lock_alpha=0.88"
  "+env.task_kwargs.rm75_hand_dynamic_close_contact_boost=0.55"
  "+env.task_kwargs.rm75_hand_dynamic_close_phase_weight=0.35"
  "+env.task_kwargs.rm75_hand_dynamic_close_phase_start=2"
  "+env.task_kwargs.rm75_hand_dynamic_close_phase_ramp=22"
  "+env.task_kwargs.rm75_hand_dynamic_close_phase_near_gate=0.26"
  "+env.task_kwargs.rm75_hand_dynamic_close_group_mode=ratio"
  "+env.task_kwargs.rm75_hand_dynamic_close_thumb_ratio=0.78"
  "+env.task_kwargs.rm75_hand_dynamic_close_pinky_ratio=0.82"
  "+env.task_kwargs.rm75_hand_dynamic_close_finger_mode=mean"
  "+env.task_kwargs.rm75_hand_precontact_close_cap=0.46"
  "+env.task_kwargs.rm75_hand_precontact_thumb_cap=0.26"
  "+env.task_kwargs.rm75_hand_precontact_pinky_cap=0.36"
  "+env.task_kwargs.rm75_hand_close_bias_weights=[0.34,0.44,1.0,1.0,0.96,0.68]"
  "env.info_keywords=${INFO_KEYS}"
  "+env.task_kwargs.reward_kwargs.pregrasp_success_thresh=0.075"
  "+env.task_kwargs.reward_kwargs.obj_com_done_thresh=0.155"
  "+env.task_kwargs.reward_kwargs.no_contact_grace_steps=14"
  "+env.task_kwargs.reward_kwargs.controller_penalty_scale=900.0"
  "+env.task_kwargs.reward_kwargs.action_penalty_scale=0.008"
  "+env.task_kwargs.reward_kwargs.reward_divisor=10.0"
  "+env.task_kwargs.reward_kwargs.finger_approach_reward_scale=0.85"
  "+env.task_kwargs.reward_kwargs.finger_approach_scale=18.0"
  "+env.task_kwargs.reward_kwargs.min_finger_approach_reward_scale=0.75"
  "+env.task_kwargs.reward_kwargs.min_finger_approach_scale=13.0"
  "+env.task_kwargs.reward_kwargs.palm_approach_reward_scale=0.60"
  "+env.task_kwargs.reward_kwargs.palm_approach_scale=6.5"
  "+env.task_kwargs.reward_kwargs.contact_reward_scale=0.50"
  "+env.task_kwargs.reward_kwargs.thumb_contact_reward_scale=1.65"
  "+env.task_kwargs.reward_kwargs.non_thumb_contact_reward_scale=1.15"
  "+env.task_kwargs.reward_kwargs.required_non_thumb_contacts=1"
  "+env.task_kwargs.reward_kwargs.object_reward_requires_contact=True"
  "+env.task_kwargs.reward_kwargs.object_reward_requires_stable_contact=False"
  "+env.task_kwargs.reward_kwargs.object_reward_contact_hold_steps=2"
  "+env.task_kwargs.reward_kwargs.no_contact_penalty=0.22"
  "env.task_kwargs.reward_kwargs.object_reward_scale=8.0"
  "env.task_kwargs.reward_kwargs.obj_err_scale=45.0"
  "+env.task_kwargs.reward_kwargs.obj_rot_term=0.10"
  "+env.task_kwargs.reward_kwargs.hand_mimic_reward_scale=2.0"
  "+env.task_kwargs.reward_kwargs.hand_mimic_scale=9.0"
  "+env.task_kwargs.reward_kwargs.hand_close_reward_scale=3.5"
  "+env.task_kwargs.reward_kwargs.hand_close_near_dist=0.120"
  "+env.task_kwargs.reward_kwargs.hand_close_palm_near_dist=0.240"
  "+env.task_kwargs.reward_kwargs.hand_close_min_finger_near_dist=0.125"
  "+env.task_kwargs.reward_kwargs.hand_close_contact_only=False"
  "+env.task_kwargs.reward_kwargs.hand_close_target=0.72"
  "+env.task_kwargs.reward_kwargs.hand_open_penalty_scale=1.6"
  "+env.task_kwargs.reward_kwargs.reference_close_reward_scale=0.7"
  "+env.task_kwargs.reward_kwargs.reference_close_penalty_scale=0.9"
  "+env.task_kwargs.reward_kwargs.reference_close_tolerance=0.13"
  "+env.task_kwargs.reward_kwargs.reference_close_start_step=4"
  "+env.task_kwargs.reward_kwargs.early_close_penalty_scale=0.8"
  "+env.task_kwargs.reward_kwargs.early_close_palm_dist=0.235"
  "+env.task_kwargs.reward_kwargs.early_close_min_finger_dist=0.130"
  "+env.task_kwargs.reward_kwargs.hand_synergy_reward_scale=1.1"
  "+env.task_kwargs.reward_kwargs.hand_synergy_penalty_scale=0.6"
  "+env.task_kwargs.reward_kwargs.hand_synergy_balance_penalty_scale=0.5"
  "+env.task_kwargs.reward_kwargs.hand_synergy_min_main_close=0.16"
  "+env.task_kwargs.reward_kwargs.hand_synergy_thumb_target_ratio=0.78"
  "+env.task_kwargs.reward_kwargs.hand_synergy_pinky_target_ratio=0.82"
  "+env.task_kwargs.reward_kwargs.stable_contact_bonus=8.0"
  "+env.task_kwargs.reward_kwargs.contact_hold_bonus_scale=4.5"
  "+env.task_kwargs.reward_kwargs.contact_hold_bonus_steps=6"
  "env.task_kwargs.reward_kwargs.lift_bonus_thresh=0.010"
  "env.task_kwargs.reward_kwargs.lift_bonus_mag=6.0"
  "+env.task_kwargs.reward_kwargs.lift_reward_scale=55.0"
  "+env.task_kwargs.reward_kwargs.lift_reward_cap=0.09"
  "+env.task_kwargs.reward_kwargs.object_xy_drift_free_thresh=0.014"
  "+env.task_kwargs.reward_kwargs.object_xy_drift_penalty_scale=18.0"
  "+env.task_kwargs.reward_kwargs.object_speed_penalty_scale=0.050"
  "+env.task_kwargs.reward_kwargs.object_tilt_free_thresh=0.24"
  "+env.task_kwargs.reward_kwargs.object_tilt_penalty_scale=6.0"
  "+env.task_kwargs.reward_kwargs.object_ang_vel_penalty_scale=0.035"
  "+env.task_kwargs.reward_kwargs.unstable_push_penalty_scale=12.0"
  "+env.task_kwargs.reward_kwargs.bad_push_done=True"
  "+env.task_kwargs.reward_kwargs.bad_push_min_step=8"
  "+env.task_kwargs.reward_kwargs.bad_push_drift_thresh=0.055"
  "+env.task_kwargs.reward_kwargs.bad_push_tilt_thresh=0.40"
  "agent.params.actor_objective=fpo"
  "agent.params.trust_region_mode=aspo"
  "agent.params.learning_rate=4.0e-6"
  "agent.params.clip_range=0.10"
  "agent.params.log_ratio_scale=0.45"
  "agent.params.cfm_diff_clip=2.2"
  "agent.params.cfm_loss_clamp=20.0"
  "agent.params.action_head_mode=flow_residual"
  "agent.params.rollout_action_noise_std=0.012"
  "agent.params.rollout_deterministic=False"
  "agent.params.eval_deterministic=False"
  "agent.params.n_steps=${N_STEPS}"
  "agent.params.batch_size=${BATCH_SIZE}"
  "agent.params.n_epochs=${N_EPOCHS}"
  "agent.params.n_samples_per_action=${N_SAMPLES}"
  "agent.params.sampling_steps=8"
  "agent.params.actor_hidden_dims=${ACTOR_DIMS}"
  "agent.params.critic_hidden_dims=${CRITIC_DIMS}"
  "agent.params.residual_head_hidden_dims=${RESIDUAL_DIMS}"
  "agent.params.activation=elu"
  "agent.params.max_grad_norm=1.0"
  "agent.params.actor_max_grad_norm=0.5"
  "agent.params.critic_max_grad_norm=2.0"
  "agent.params.curriculum_pregrasp_threshold=0.95"
  "agent.params.curriculum_stage2_metric=eval/mean_rm75_grasp_score"
  "agent.params.curriculum_stage2_threshold=10.0"
  "agent.params.best_metric=eval/mean_rm75_grasp_score"
  "agent.params.degrade_metric=eval/mean_rm75_grasp_score"
  "agent.params.save_best_model=True"
  "agent.params.rollback_to_best_on_degrade=True"
  "agent.params.rollback_patience=5"
  "agent.params.degrade_threshold=6.0"
  "n_envs=${N_ENVS}"
  "n_eval_envs=${N_EVAL_ENVS}"
  "eval_n_episodes=${EVAL_N_EPISODES}"
  "total_timesteps=${TOTAL_TIMESTEPS}"
  "eval_freq=${EVAL_FREQ}"
  "save_freq=${SAVE_FREQ}"
  "restore_checkpoint_freq=${RESTORE_FREQ}"
  "wandb.project=${WANDB_PROJECT:-vividex_rm75_active6}"
  "wandb.group=${WANDB_GROUP:-rm75_active6_rfpo}"
  "wandb.sweep_name_prefix=${RUN_NAME}"
  "hydra.run.dir=${RUN_DIR}"
)

if [[ -n "${EXTRA_OVERRIDES:-}" ]]; then
  read -r -a EXTRA_OVERRIDE_ARGS <<< "${EXTRA_OVERRIDES}"
  CMD+=("${EXTRA_OVERRIDE_ARGS[@]}")
fi

printf '[active6-rfpo] command: %q ' "${CMD[@]}"
printf '\n'
"${CMD[@]}"
