#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${SCRIPT_DIR}/../.." && pwd)"

DEFAULT_RESUME="${REPO}/.local_runs/rm75_active6_v5_train_postcontactwrist_950k_20260625_211654/models/best.pt"
RESUME_MODEL="${RESUME_MODEL:-${DEFAULT_RESUME}}"

if [[ ! -f "${RESUME_MODEL}" ]]; then
  echo "Missing RESUME_MODEL: ${RESUME_MODEL}" >&2
  exit 1
fi

export VIVIDEX_HEADLESS_NO_RENDER="${VIVIDEX_HEADLESS_NO_RENDER:-1}"
export ACTIVE6_URDF="${ACTIVE6_URDF:-${REPO}/assets/robot/rm75_inspire_right/urdf/rm75_inspire_hand_right_active6_nocyl.urdf}"

# Keep the contacts sticky enough for diagnosis, but avoid the high-force pop
# seen in the lift-contact v9 branch.
export VIVIDEX_RM75_FINGER_FORCE_LIMIT="${VIVIDEX_RM75_FINGER_FORCE_LIMIT:-100}"
export VIVIDEX_RM75_FINGER_STIFFNESS="${VIVIDEX_RM75_FINGER_STIFFNESS:-380}"
export VIVIDEX_RM75_FINGER_DAMPING="${VIVIDEX_RM75_FINGER_DAMPING:-85}"
export VIVIDEX_RM75_STATIC_FRICTION="${VIVIDEX_RM75_STATIC_FRICTION:-4.0}"
export VIVIDEX_RM75_DYNAMIC_FRICTION="${VIVIDEX_RM75_DYNAMIC_FRICTION:-3.0}"
export VIVIDEX_RM75_RESTITUTION="${VIVIDEX_RM75_RESTITUTION:-0.0}"
export VIVIDEX_YCB_STATIC_FRICTION="${VIVIDEX_YCB_STATIC_FRICTION:-4.0}"
export VIVIDEX_YCB_DYNAMIC_FRICTION="${VIVIDEX_YCB_DYNAMIC_FRICTION:-3.0}"
export VIVIDEX_YCB_RESTITUTION="${VIVIDEX_YCB_RESTITUTION:-0.0}"

export RUN_NAME="${RUN_NAME:-rm75_active6_v10_wrist_stop_$(date +%Y%m%d_%H%M%S)}"
export TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-925000}"
export EVAL_FREQ="${EVAL_FREQ:-25000}"
export EVAL_N_EPISODES="${EVAL_N_EPISODES:-20}"
export SAVE_FREQ="${SAVE_FREQ:-50000}"
export RESTORE_FREQ="${RESTORE_FREQ:-50000}"
export N_ENVS="${N_ENVS:-8}"
export N_EVAL_ENVS="${N_EVAL_ENVS:-2}"

OVERRIDES=(
  "resume_model=${RESUME_MODEL}"
  "agent.params.resume_load_optimizer=False"
  "++env.task_kwargs.rm75_default_approach_delta=[0.0,-0.055,0.0]"
  "++env.task_kwargs.rm75_arm_action_scale=0.18"
  "++env.task_kwargs.rm75_post_pregrasp_arm_ramp_steps=18"
  "++env.task_kwargs.rm75_post_pregrasp_arm_scale_start=0.018"
  "++env.task_kwargs.rm75_post_pregrasp_arm_scale_end=0.18"
  "++env.task_kwargs.rm75_post_pregrasp_hold_until_stable=True"
  "++env.task_kwargs.rm75_post_pregrasp_hold_arm_scale=0.026"
  "++env.task_kwargs.rm75_post_pregrasp_required_stable_hold_steps=3"
  "++env.task_kwargs.rm75_post_pregrasp_project_to_object=True"
  "++env.task_kwargs.rm75_post_pregrasp_project_until_stable=True"
  "++env.task_kwargs.rm75_post_pregrasp_project_tangent_scale=0.12"
  "++env.task_kwargs.rm75_post_pregrasp_project_max_approach_speed=0.045"
  "++env.task_kwargs.rm75_post_pregrasp_project_max_retreat_speed=0.008"
  "++env.task_kwargs.rm75_wrist_angular_bias=[-0.08,0.0,-0.25]"
  "++env.task_kwargs.rm75_wrist_angular_bias_start_step=0"
  "++env.task_kwargs.rm75_wrist_angular_bias_end_step=45"
  "++env.task_kwargs.rm75_post_contact_wrist_bias=[0.0,0.0,0.0]"
  "++env.task_kwargs.rm75_post_contact_lift_assist=False"
  "++env.task_kwargs.rm75_post_stable_lift_only=True"
  "++env.task_kwargs.rm75_post_stable_max_xy_speed=0.006"
  "++env.task_kwargs.rm75_post_stable_max_down_speed=0.001"
  "++env.task_kwargs.rm75_post_stable_max_up_speed=0.024"
  "++env.task_kwargs.rm75_post_stable_lift_bias=0.003"
  "++env.task_kwargs.rm75_post_stable_max_angular_speed=0.10"
  "++env.task_kwargs.rm75_hand_close_bias=0.012"
  "++env.task_kwargs.rm75_hand_dynamic_close_bias=0.68"
  "++env.task_kwargs.rm75_hand_dynamic_close_start=0.250"
  "++env.task_kwargs.rm75_hand_dynamic_close_full=0.085"
  "++env.task_kwargs.rm75_hand_dynamic_close_gate_mode=envelope"
  "++env.task_kwargs.rm75_hand_dynamic_close_requires_contact=False"
  "++env.task_kwargs.rm75_hand_dynamic_close_warmup_steps=2"
  "++env.task_kwargs.rm75_hand_dynamic_close_ramp_steps=22"
  "++env.task_kwargs.rm75_hand_dynamic_close_alpha_smooth=0.35"
  "++env.task_kwargs.rm75_hand_dynamic_close_contact_hold_steps=2"
  "++env.task_kwargs.rm75_hand_dynamic_close_contact_lock_alpha=0.82"
  "++env.task_kwargs.rm75_hand_dynamic_close_contact_boost=0.42"
  "++env.task_kwargs.rm75_hand_dynamic_close_group_mode=ratio"
  "++env.task_kwargs.rm75_hand_dynamic_close_thumb_ratio=0.72"
  "++env.task_kwargs.rm75_hand_dynamic_close_pinky_ratio=0.80"
  "++env.task_kwargs.rm75_hand_precontact_close_cap=0.42"
  "++env.task_kwargs.rm75_hand_precontact_thumb_cap=0.24"
  "++env.task_kwargs.rm75_hand_precontact_pinky_cap=0.32"
  "++env.task_kwargs.rm75_hand_close_bias_weights=[0.34,0.44,0.92,0.92,0.90,0.66]"
  "++env.task_kwargs.reward_kwargs.no_contact_grace_steps=18"
  "++env.task_kwargs.reward_kwargs.required_non_thumb_contacts=1"
  "++env.task_kwargs.reward_kwargs.contact_reward_scale=0.35"
  "++env.task_kwargs.reward_kwargs.thumb_contact_reward_scale=1.6"
  "++env.task_kwargs.reward_kwargs.non_thumb_contact_reward_scale=1.8"
  "++env.task_kwargs.reward_kwargs.stable_contact_bonus=16.0"
  "++env.task_kwargs.reward_kwargs.contact_hold_bonus_scale=10.0"
  "++env.task_kwargs.reward_kwargs.contact_hold_bonus_steps=8"
  "++env.task_kwargs.reward_kwargs.object_reward_requires_contact=True"
  "++env.task_kwargs.reward_kwargs.object_reward_requires_stable_contact=True"
  "++env.task_kwargs.reward_kwargs.object_reward_contact_hold_steps=2"
  "++env.task_kwargs.reward_kwargs.object_reward_scale=7.5"
  "++env.task_kwargs.reward_kwargs.obj_err_scale=38.0"
  "++env.task_kwargs.reward_kwargs.hand_close_reward_scale=3.0"
  "++env.task_kwargs.reward_kwargs.hand_close_target=0.70"
  "++env.task_kwargs.reward_kwargs.hand_open_penalty_scale=1.8"
  "++env.task_kwargs.reward_kwargs.hand_synergy_reward_scale=1.0"
  "++env.task_kwargs.reward_kwargs.hand_synergy_penalty_scale=0.7"
  "++env.task_kwargs.reward_kwargs.hand_synergy_balance_penalty_scale=0.5"
  "++env.task_kwargs.reward_kwargs.lift_bonus_thresh=0.006"
  "++env.task_kwargs.reward_kwargs.lift_bonus_mag=8.0"
  "++env.task_kwargs.reward_kwargs.lift_reward_scale=80.0"
  "++env.task_kwargs.reward_kwargs.lift_reward_cap=0.08"
  "++env.task_kwargs.reward_kwargs.object_xy_drift_free_thresh=0.016"
  "++env.task_kwargs.reward_kwargs.object_xy_drift_penalty_scale=24.0"
  "++env.task_kwargs.reward_kwargs.object_tilt_free_thresh=0.24"
  "++env.task_kwargs.reward_kwargs.object_tilt_penalty_scale=10.0"
  "++env.task_kwargs.reward_kwargs.object_speed_penalty_scale=0.060"
  "++env.task_kwargs.reward_kwargs.object_ang_vel_penalty_scale=0.040"
  "++env.task_kwargs.reward_kwargs.unstable_push_penalty_scale=16.0"
  "++env.task_kwargs.reward_kwargs.bad_push_done=True"
  "++env.task_kwargs.reward_kwargs.bad_push_min_step=8"
  "++env.task_kwargs.reward_kwargs.bad_push_drift_thresh=0.060"
  "++env.task_kwargs.reward_kwargs.bad_push_tilt_thresh=0.36"
  "agent.params.best_metric=eval/mean_rm75_task_score"
  "agent.params.degrade_metric=eval/mean_rm75_task_score"
  "agent.params.curriculum_stage2_metric=eval/mean_rm75_task_score"
  "agent.params.curriculum_stage2_threshold=5.0"
  "agent.params.rollback_to_best_on_degrade=False"
  "agent.params.eval_deterministic=True"
  "agent.params.rollout_action_noise_std=0.008"
  "agent.params.learning_rate=2.5e-6"
  "agent.params.clip_range=0.10"
  "agent.params.log_ratio_scale=0.40"
  "agent.params.cfm_diff_clip=2.2"
)

if [[ -n "${ACTIVE6_EXTRA_OVERRIDES:-}" ]]; then
  read -r -a ACTIVE6_EXTRA_OVERRIDE_ARGS <<< "${ACTIVE6_EXTRA_OVERRIDES}"
  OVERRIDES+=("${ACTIVE6_EXTRA_OVERRIDE_ARGS[@]}")
fi

export EXTRA_OVERRIDES="${OVERRIDES[*]}"

cd "${REPO}"
exec bash scripts/local/rm75_active6_rfpo_train.sh
